### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ArtistScope** [jameswilson/asp-vbscript-cms#2]
re... <% Server.Execute("../core/include/application.asp") %> on default.asp

/core/include/application.asp is missing from the download ZIP.

**Comment by jameswilson** [comment]
I did a search for `<% Server.Execute("../core/include/application.asp") %>` and found one file that does contain an incorrect relative path to the file, which is the `core/error_docs/400.asp` file. But not the default.asp.
